"""account_number field added to bank_accounts table

Revision ID: 082d3b51c8c0
Revises: 0af4b932ab46
Create Date: 2025-10-16 19:43:27.712969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082d3b51c8c0'
down_revision = '0af4b932ab46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_column('account_number')

    # ### end Alembic commands ###
