"""Remove code column from bank_accounts

Revision ID: 0af4b932ab46
Revises: 414fa305b588
Create Date: 2025-10-15 23:34:04.094576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0af4b932ab46'
down_revision = '414fa305b588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_column('code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
