"""add description column to Expense

Revision ID: 28186827616a
Revises: 082d3b51c8c0
Create Date: 2025-11-16 13:02:37.058115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28186827616a'
down_revision = '082d3b51c8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
